using System.Collections;
using System.Collections.Generic;
using UnityEngine;

[RequireComponent(typeof(AudioSource))]
public class PlayerAudio : MonoBehaviour
{
    [SerializeField] AudioSource audioSource;
    // Start is called before the first frame update
    void Start()
    {
        audioSource = GetComponent<AudioSource>();
    }

    // Update is called once per frame
    
     void Update()
     {
        if (GameManager.Instance.gameState == GameManager.GameStates.Play)
        {
            if (Input.GetKeyDown(KeyCode.O))
            {
            audioSource.Play();
            }
        }
     }
}
